package co.edu.itp.ciecyt.domain.enumeration;

/**
 * Estados del flujo de trabajo de grado.
 */
public enum EnumEstadoProyecto {
    PREINSCRITA,
    EN_ELABORACION_PROPUESTA,
    EN_REVISION_ASESOR,
    CORRECCIONES_ASESOR,
    APROBADA_POR_ASESOR,
    EN_REVISION_JURADO_PROPUESTA,
    CORRECCIONES_JURADO_PROPUESTA,
    NO_VIABLE,
    VIABLE,
    EN_ELABORACION_PROYECTO,
    EN_REVISION_JURADO_PROYECTO,
    CORRECCIONES_JURADO_PROYECTO,
    LISTO_PARA_SUSTENTAR,
    SUSTENTACION_PROGRAMADA,
    SUSTENTACION_REALIZADA,
    EN_EVALUACION_SUSTENTACION,
    AJUSTES_SUSTENTACION,
    NOTA_DEFINITIVA,
    FINALIZADO
}
