export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  ASESOR = 'ROLE_ASESOR',
  JURADO = 'ROLE_JURADO',
  CIECYT = 'ROLE_CIECYT',
  ANONYMOUS = 'ROLE_ANONYMOUS',
  ESTUDIANTE = 'ROLE_ESTUDIANTE',
}
